# Pindah ke port 9000 yang biasanya jarang dipakai
server.port=9000

# Konfigurasi Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_cafe_kel3?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Cache Thymeleaf dimatikan
spring.thymeleaf.cache=false